### ISSUE TITLE
2 and sometimes 3 copies of the backlinks show up

### ISSUE THREAD

**Issue by GitMurf** [mrjackphil/obsidian-backlinks-in-document#10]
Hi, for some reason since the last update a couple days ago, 2 or 3 copies of the backlinks shows up below my notes. Do you know what I may have done to cause this?

![image](https://user-images.githubusercontent.com/64155612/108812520-1dad2d00-7564-11eb-9e2d-414947c0438c.png)

**Comment by gasminder** [comment]
Same here. Have uninstalled and reinstalled with issue continuing.

**Comment by mrjackphil** [comment]
Hey, does anyone have that issue? Can't reproduce. Feel free to reopen when I'll appear again.

**Comment by rishifter** [comment]
I still have this! I am not using the native one since it works only in preview AND it doesn't work on all files at once. So this plugin is still relevant to me and it's the first time actually I'm getting two backlinks pane. Tried disabling/enabling, restarting and closing all notes and opening it again. Didn't fix it. Willing to share any more info to help fix it.
